project:
  type: website

website:
  favicon: img/DSI_Avatar_03.ico
  title: "Data Science at Chico State"
  navbar:
    logo: img/DSI_Avatar_03.ico
    left:
      - text: About
        href: about.qmd
      - text: Wildcat Data Hub
        href: datahub/datahub.qmd
      - text: Projects
        href: projects.qmd
      - text: News & Events
        href: news.qmd
      - text: Community Coding
        href: communityCoding.qmd
      - text: NorCal DataFest!
        href: https://norcaldatafest.netlify.app/
    right:
      - text: Mission
        href: https://www.csuchico.edu/datascience/mission.shtml
      - icon: github
        menu:
          - text: CSUC DSI
            url: https://github.com/csucdsi
          - text: Math 490
            url: https://github.com/DATA-490
      - icon: search


format:
  html:
    highlight-style: a11y
    theme:
      light: Chico_Light.scss
    highlight: pygments
    toc: true
    code-copy: true
    code-overflow: scroll
    callout-icon: false
    page-layout: full
    include-after-body: _footer.html
    css: styles.css

execute:
  freeze: true
  echo: false
  warning: false
